### ISSUE TITLE
Use mask image

### ISSUE THREAD

**Issue by andrewharvey** [cheind/inpaint#10]
Is there any way to run this providing a mask image instead of using a GUI to create the mask?

**Comment by cheind** [comment]
Hi, the application currently does not support it, but the library of course does. You could just load two images at startup and use one as mask and then call

```c++
while(inpainter.hasMoreSteps())
  inpainter.step()
```

**Comment by andrewharvey** [comment]
Thanks @cheind. I ended up using gmic which works on the command line with a mask image https://github.com/andrewharvey/lg360-mapillary-helpers/blob/master/lg360_inpaint_single#L21

**Comment by cheind** [comment]
Ok, probably the easier way! Best,
Christoph

**Comment by xizi** [comment]
@cheind could you give a tutorial about how to run this providing a mask image？
