### ISSUE TITLE
Compling error

### ISSUE THREAD

**Issue by QuantumLiu** [cheind/inpaint#11]
Ubuntu 16.04,OpenCV3.3
Maybe caused by the version of my OpenCV?
Which version you used?
`[ 23%] Built target inpaint
[ 35%] Built target patch_match
[ 47%] Built target inpaint_benchmarks
[ 58%] Built target inpaint_image_criminisi
[ 64%] Building CXX object CMakeFiles/inpaint_tests.dir/tests/patch_match.cpp.o
/home/quantumliu/cv/inpaint/tests/patch_match.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____48()’:
/home/quantumliu/cv/inpaint/tests/patch_match.cpp:55:43: error: ‘FILLED’ is not a member of ‘cv’
     cv::rectangle(mask, r, cv::Scalar(0), cv::FILLED);
                                           ^
CMakeFiles/inpaint_tests.dir/build.make:182: recipe for target 'CMakeFiles/inpaint_tests.dir/tests/patch_match.cpp.o' failed
make[2]: *** [CMakeFiles/inpaint_tests.dir/tests/patch_match.cpp.o] Error 1
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/inpaint_tests.dir/all' failed
make[1]: *** [CMakeFiles/inpaint_tests.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by cheind** [comment]
Hi, haven't had a chance to look at it. Will do so this weekend.

**Comment by cheind** [comment]
That's strage. Just tested with VisualStudio 14, OpenCV 3.3 and did not encounter any errors.
Also, `cv::FILLED` should be defined in OpenCV 3.3 according to the [docs](https://docs.opencv.org/trunk/d0/de1/group__core.html#ggaf076ef45de481ac96e0ab3dc2c29a777a89c5f6beef080e6df347167f85e07b9e) (see cv::LineTypes).
```
1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>  Checking Build System
1>  CMake does not need to re-run because inpaint_vc14/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: inpaint, Configuration: Release x64 ------
2>  Building Custom Rule inpaint/CMakeLists.txt
2>  CMake does not need to re-run because inpaint_vc14\CMakeFiles\generate.stamp is up-to-date.
2>  criminisi_inpainter.cpp
2>  template_match_candidates.cpp
2>  patch_match.cpp
2>  Generating Code...
2>  inpaint.vcxproj -> inpaint_vc14\Release\inpaint.lib
3>------ Build started: Project: inpaint_benchmarks, Configuration: Release x64 ------
4>------ Build started: Project: inpaint_image_criminisi, Configuration: Release x64 ------
5>------ Build started: Project: inpaint_tests, Configuration: Release x64 ------
6>------ Build started: Project: patch_match, Configuration: Release x64 ------
3>  Building Custom Rule inpaint/CMakeLists.txt
3>  CMake does not need to re-run because inpaint_vc14\CMakeFiles\generate.stamp is up-to-date.
3>  patch.cpp
5>  Building Custom Rule inpaint/CMakeLists.txt
4>  Building Custom Rule inpaint/CMakeLists.txt
5>  CMake does not need to re-run because inpaint_vc14\CMakeFiles\generate.stamp is up-to-date.
4>  CMake does not need to re-run because inpaint_vc14\CMakeFiles\generate.stamp is up-to-date.
4>  inpaint_image_criminisi.cpp
5>  gradient.cpp
6>  Building Custom Rule inpaint/CMakeLists.txt
6>  CMake does not need to re-run because inpaint_vc14\CMakeFiles\generate.stamp is up-to-date.
6>  patch_match.cpp
4>  inpaint_image_criminisi.vcxproj -> inpaint_vc14\Release\inpaint_image_criminisi.exe
6>  patch_match.vcxproj -> inpaint_vc14\Release\patch_match.exe
5>  patch.cpp
5>  integral.cpp
5>  criminisi_inpainter.cpp
3>  inpaint_benchmarks.vcxproj -> inpaint_vc14\Release\inpaint_benchmarks.exe
5>  template_match_candidates.cpp
5>  patch_match.cpp
5>  Generating Code...
5>  inpaint_tests.vcxproj -> inpaint_vc14\Release\inpaint_tests.exe
7>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
7>  Building Custom Rule inpaint/CMakeLists.txt
7>  CMake does not need to re-run because inpaint_vc14\CMakeFiles\generate.stamp is up-to-date.
========== Build: 7 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by QuantumLiu** [comment]
thx~~
