### ISSUE TITLE
Linker Issue while building the source in Windows

### ISSUE THREAD

**Issue by harshithabk** [cheind/inpaint#12]
Hi,
I am trying to build the source code with the below environment set-up:
1) Open CV version - opencv-2.4.11.exe
2) Visual studio 2013
3) The mode set to build the code is Debug x64.
4) Also, linked all open CV libraries [.dll files] present in the path "opencv\build\x64\vc12\bin".
5) I have also added "opencv\build\x64\vc12\lib" under the section "Linker->General->Additional Library Directories"
6) I have also added "opencv\build\include", "inc\inpaint", "tests" under the section "C/C++->General"
7) I have added all the files from "src" & "catch.hpp", "random_testdata.h" from "tests" to the visual studio project.

When i tried building the code, i obtained the following linker errors.
1) error LNK1120: 4 unresolved externals	20171219\windows\inpainting\x64\Debug\inpainting.exe	inpainting
2) error LNK2019: unresolved external symbol "public: int __cdecl cv::_InputArray::cols(void)const " (?cols@_InputArray@cv@@QEBAHXZ) referenced in function "void __cdecl Inpaint::meanShift(class cv::_InputArray const &,class cv::_InputArray const &,class cv::_InputArray const &,class cv::_OutputArray const &,class cv::_OutputArray const &,class cv::_OutputArray const &,float,int,bool,bool,bool)" (?meanShift@Inpaint@@YAXAEBV_InputArray@cv@@00AEBV_OutputArray@3@11MH_N22@Z)	20171219\windows\inpainting\mean_shift.obj	inpainting
3) error LNK2019: unresolved external symbol "public: int __cdecl cv::_InputArray::rows(void)const " (?rows@_InputArray@cv@@QEBAHXZ) referenced in function "void __cdecl Inpaint::meanShift(class cv::_InputArray const &,class cv::_InputArray const &,class cv::_InputArray const &,class cv::_OutputArray const &,class cv::_OutputArray const &,class cv::_OutputArray const &,float,int,bool,bool,bool)" (?meanShift@Inpaint@@YAXAEBV_InputArray@cv@@00AEBV_OutputArray@3@11MH_N22@Z)	20171219\windows\inpainting\mean_shift.obj	inpainting
4) error LNK2019: unresolved external symbol "public: void * __cdecl cv::_InputArray::getObj(void)const " (?getObj@_InputArray@cv@@QEBAPEAXXZ) referenced in function "void __cdecl Inpaint::imagePyramid(class cv::_InputArray const &,class cv::_OutputArray const &,class cv::Size_<int>,int)" (?imagePyramid@Inpaint@@YAXAEBV_InputArray@cv@@AEBV_OutputArray@3@V?$Size_@H@3@H@Z)	20171219\windows\inpainting\pyramid.obj	inpainting
5) error LNK2019: unresolved external symbol main referenced in function __tmainCRTStartup	20171219\windows\inpainting\MSVCRTD.lib(crtexe.obj)	inpainting  

Could you please help me resolve this error? 
We need additional information. 
Could you please let us know if this code can take care about object overlapping scenario?

**Comment by cheind** [comment]
Hi, please try to use OpenCV 3.x and see if the error persist. Not sure what you mean by overlapping scenario.

**Comment by harshithabk** [comment]
Hi,  
I installed OpenCV 3.4 [opencv-3.4.0-vc14_vc15.exe].
This was compatible with Visual studio 2015 & 2017.
I tried building the source code with Visual studio 2015.
However still in getting following build errors:
1) Error LNK2019 : unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)  	20171219\windows\2015Sln\inpainting_Ashish\MSVCRTD.lib(exe_main.obj)	 
2) Error LNK1120 : 1 unresolved externals  	20171219\windows\2015Sln\inpainting_Ashish\x64\Debug\inpainting_Ashish.exe	
Kindly help me in this regard?

Also with respect to previous comment `overlapping scenario` is, when an object A is overlapping on object B, if I want to remove object A & object B needs to be reconstructed, does this code support this scenario?

**Comment by harshithabk** [comment]
Hi,  
I could build the source code.
However, when i trying to run the executable, I get an error `The program can't start because opencv_world340d.dll is missing from your computer`  
However, i observed that `opencv_world340d.dll` is present in `opencv\build\x64\vc14\bin`.
I am trying to resolve this?
Do you have any suggestions regarding the same?

**Comment by cheind** [comment]
Yes, but that file is not part of your library lookup path. Easiest way is to copy that file to the directory of your executable file.

**Comment by harshithabk** [comment]
Hi, 
I am sorry i forgot to share you the update.
Yesterday only, I copied the `opencv_world340d.dll` from opencv\build\x64\vc14\bin to the inpainting.exe directory.  
In the command line argument I am passing an image of PNG format & size 660x495.
However, the window for `Image Inpaint` pops up to modify patchsize & stencilsize.
And then the source code crashes with the following assertion error:  
OpenCV Error: Assertion failed (size.width>0 && size.height>0) in cv::imshow, file C:\build\master_winpack-build-win64-vc14\opencv\modules\highgui\src\window.cpp, line 331
I am trying to resolve this. 
Any idea why this error has come up?

**Comment by harshithabk** [comment]
Hi,  
I could execute the source code without assertion error.
Gave the complete path of input file & it worked.
I also referred this https://github.com/opencv/opencv/issues/9511
Thank you.

**Comment by harshithabk** [comment]
Hi,
I could execute and perform inpainting in Debug x64 mode in windows machine.
However, in Release x64 mode, there is heap corruption during execution.
I am trying to resolve this.
Could you help us in this regard?

**Comment by cheind** [comment]
Seems like you forgot to initialize some of your variables. Usually in debug mode the compiler does this for you, but not so in release mode.

**Comment by harshithabk** [comment]
Hi,
I understand your point.
But currently, i am trying to execute the source code as it is.
I have not done any modification from my end.

**Comment by harshithabk** [comment]
Hi, 
I could resolve this issue.
Earlier I had added both opencv_world340.lib & opencv_world340d.lib for Debug and Release modes.
Now I modified such that opencv_world340.lib is added only for release mode & opencv_world340d.lib is added for Debug mode.
Thank you very much.

**Comment by cheind** [comment]
yes that's correct. If you use a build generator such as CMake this should be handled more or less automatically.
