### ISSUE TITLE
CMake on Windows 10

### ISSUE THREAD

**Issue by slashpot** [cheind/inpaint#2]
Hello, I'm using Windows 10 with Visual Studio 2015 x64. However when I use CMake to configure, It can't find OpenCV_DIR. I tried to install OpenCV 2.4.13 and Opencv 3.1, and tried to  manually select path for OpenCV_DIR too, but it doesn't work...  
I'm wandering that can I cmake on Windows 10? or maybe I did it in a wrong way?  
Thank you.

**Comment by cheind** [comment]
You need to set the OpenCV_DIR to the **build** directory of OpenCV. See here

http://answers.opencv.org/question/12074/cmake-opencv_dir/

**Comment by slashpot** [comment]
Thanks for your advise, but somehow it needs more than set  OpenCV_DIR path.  
Actually I manually add inpaint files to my project and it works, and the result is pretty amazing!But I think I still need to report what kind of error I get.
This is the error I encounter after setting the OpenCV_DIR:
```
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.
```
I think cmake needs a FindOpenCV.cmake file,you can check here
http://stackoverflow.com/questions/8711109/could-not-find-module-findopencv-cmake-error-in-configuration-process

**Comment by cheind** [comment]
Modern OpenCV does not require a finder module, but rather provides all the necessary package files that allow CMAKE to figure out what is needed. Do you see a OpenCVConfig.cmake inside the build directory of OpenCV? If so, set the OpenCV_DIR to that directory and rerun CMAKE.

**Comment by cheind** [comment]
@slashpot any progress?

**Comment by slashpot** [comment]
Sorry for late response, after I point OpenCV_DIR to build directory and rerun CMAKE I still got error and I couldn't figure out why. Maybe it's my own fault somewhere.
Error message is here:
```
OpenCV ARCH: x86
OpenCV RUNTIME: vc14
OpenCV STATIC: ON
CMake Warning at D:/opencv/build/OpenCVConfig.cmake:166 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)


CMake Error at CMakeLists.txt:10 (find_package):
  Found package configuration file:

    D:/opencv/build/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.


Configuring incomplete, errors occurred!
See also "D:/Download/inpaint-master/build/CMakeFiles/CMakeOutput.log".
```

**Comment by cheind** [comment]
It seems like OpenCV does not provide vc14 complaint 32bit binaries. Could
you try to CMAKE for x64bit?

Stan Lin <notifications@github.com> schrieb am Mi., 30. Nov. 2016 um
09:30 Uhr:

**Comment by slashpot** [comment]
It works!I specify the wrong generator, what a stupid mistake I made.Thanks for your help very much!
By the way, does this inpainter can only used for 8-bit image?Is it possible that I can modify the code to inpaint 32-bit image?

**Comment by cheind** [comment]
Good question - I would think that should be easily possible if not already supported. Try to hand it floating point image and see what happens (if not, I happily would accept pull requests). I'll close this issue for now, reopen if needed.

Best,
Christoph
