### ISSUE TITLE
Maximum value for patchSize? (Exception: -215:Assertion failed in function 'copyTo')

### ISSUE THREAD

**Issue by codenia** [cheind/inpaint#23]
Thank you for the amazing library. It works brilliantly. 
If I use a value greater than 30 for patchSize, then the following exception is thrown:

`(cv::Exception &) e = 0x0000000283732080 (msg = "OpenCV(4.7.0-dev) /source/opencv/modules/core/src/copy.cpp:442: error: (-215:Assertion failed) size() == mask.size() in function 'copyTo'\n", code = -215, err = "size() == mask.size()", func = "copyTo", file = "/source/opencv/modules/core/src/copy.cpp", line = 442)`

It happens in the following function:

```
    void CriminisiInpainter::propagatePatch(cv::Point target, cv::Point source)
    {
        cv::Mat_<uchar> copyMask = centeredPatch<PATCHFLAGS>(_targetRegion, target.y, target.x, _halfPatchSize);

	    centeredPatch<PATCHFLAGS>(_image, source.y, source.x, _halfPatchSize).copyTo(
		    centeredPatch<PATCHFLAGS>(_image, target.y, target.x, _halfPatchSize), 
		    copyMask);

	    centeredPatch<PATCHFLAGS>(_isophoteX, source.y, source.x, _halfPatchSize).copyTo(
		    centeredPatch<PATCHFLAGS>(_isophoteX, target.y, target.x, _halfPatchSize), 
		    copyMask);		

	    centeredPatch<PATCHFLAGS>(_isophoteY, source.y, source.x, _halfPatchSize).copyTo(
		    centeredPatch<PATCHFLAGS>(_isophoteY, target.y, target.x, _halfPatchSize), 
		    copyMask);

	    float cPatch = _confidence.at<float>(target);
	    centeredPatch<PATCHFLAGS>(_confidence, target.y, target.x, _halfPatchSize).setTo(cPatch, copyMask);
	
	    copyMask.setTo(0);
    }
```

Is there a maximum value for the patchSize? What could be the reason for the incorrect calculation of the values?

**Comment by YashSharmaas** [comment]
Hey! When I built the Java Android Application and tried to run this native app then it throws the same have you resolved this error you are encountering if yes please provide me the solution to avoide these types of issue

```
cv::error()             com...timediaco.opencvnativeinpaint  E  OpenCV(4.7.0-dev) Error: Assertion failed (channels() == CV_MAT_CN(dtype)) in copyTo, file /home/ci/opencv/modules/core/src/copy.cpp, line 320
2023-12-14 12:08:45.078 32096-32096 libc++abi               com...timediaco.opencvnativeinpaint  E  terminating with uncaught exception of type cv::Exception: OpenCV(4.7.0-dev) /home/ci/opencv/modules/core/src/copy.cpp:320: error: (-215:Assertion failed) channels() == CV_MAT_CN(dtype) in function 'copyTo'
2023-12-14 12:08:45.078 32096-32096 libc                    com...timediaco.opencvnativeinpaint  A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 32096 (cvnativeinpaint), pid 32096 (cvnativeinpaint)
2023-12-14 12:08:45.142  7636-7636  DEBUG                   pid-7636                             A  Process name is com.example.yrmultimediaco.opencvnativeinpaint, not key_process
2023-12-14 12:08:45.142  7636-7636  DEBUG                   pid-7636                             A  pid: 32096, tid: 32096, name: cvnativeinpaint  >>> com.example.yrmultimediaco.opencvnativeinpaint <<<
2023-12-14 12:08:45.143  7636-7636  DEBUG                   pid-7636                             A        #01 pc 00000000007058ac  /data/app/~~mol1b39XPd2lQ3pIGZqx1A==/com.example.yrmultimediaco.opencvnativeinpaint-bIbfrIG3G9YTwrXkklU6sg==/base.apk!libnative-lib.so (offset 0x19c000) (BuildId: ef90c023c0c038f238eb46ac257ebc1975e91766)

```

**Comment by codenia** [comment]
This is the crash described here: https://github.com/cheind/inpaint/issues/17

The solution is to replace this line in "void CriminisiInpainter::initialize()"

        `cv::rectangle(_targetRegion, cv::Rect(0, 0, _targetRegion.cols, _targetRegion.rows), cv::Scalar(0), _halfMatchSize);`

with this code:

```
        // The new code that prevents the exception.
        cv::rectangle(_targetRegion, cv::Rect(0, 0, _targetRegion.cols, _halfMatchSize), cv::Scalar(0), -1); // Top
        cv::rectangle(_targetRegion, cv::Rect(0, 0, _halfMatchSize, _targetRegion.rows), cv::Scalar(0), -1); // Left
        cv::rectangle(_targetRegion, cv::Rect(_targetRegion.cols - _halfMatchSize, 0, _targetRegion.cols, _targetRegion.rows), cv::Scalar(0), -1); // Bottom
        cv::rectangle(_targetRegion, cv::Rect(0, _targetRegion.rows - _halfMatchSize, _targetRegion.cols, _targetRegion.rows), cv::Scalar(0), -1); // Right
```

**Comment by codenia** [comment]
The solution is described in more detail here: https://github.com/cheind/inpaint/issues/17

**Comment by YashSharmaas** [comment]
Hey! when I try to draw the mask over the image then it will throw me the error so below I am trying to providing the if you found where I am doing wrong so provide me that solution also the function which I am trying to using there is none OutputArray so analyze my java native code and help me to resolve that issue


Main Activity code
`        srcBitmap = BitmapFactory.decodeResource(this.getResources(), R.drawable.elephant);
 imageView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                switch (event.getAction()) {
                    case MotionEvent.ACTION_DOWN:
                        // Initialize the source mask bitmap
                        if (srcBitmap != null) {
                            sourceMaskBitmap = srcBitmap.copy(srcBitmap.getConfig(), true);
                            targetMaskBitmap = Bitmap.createBitmap(srcBitmap.getWidth(), srcBitmap.getHeight(), srcBitmap.getConfig());
                        }
                        break;
                    case MotionEvent.ACTION_MOVE:
                        // Update the source mask bitmap based on user interaction
                        if (sourceMaskBitmap != null) {
                            Canvas canvas = new Canvas(sourceMaskBitmap);
                            Paint paint = new Paint();
                            paint.setColor(Color.WHITE);
                            paint.setStyle(Paint.Style.FILL);
                            canvas.drawCircle(event.getX(), event.getY(), 20, paint); // Adjust size as needed
                            imageView.setImageBitmap(sourceMaskBitmap); // Show the source mask on imageView
                        }
                        break;
                    // Handle other touch actions if needed
                }
                return true;
            }
        }); inPaint.setOnClickListener(v -> {
            if (srcBitmap != null && sourceMaskBitmap != null && targetMaskBitmap != null) {

                mProgressBar.setVisibility(View.VISIBLE);

                // Check if mask bitmaps match the input image size
                if (srcBitmap.getWidth() == sourceMaskBitmap.getWidth() &&
                        srcBitmap.getHeight() == sourceMaskBitmap.getHeight() &&
                        srcBitmap.getWidth() == targetMaskBitmap.getWidth() &&
                        srcBitmap.getHeight() == targetMaskBitmap.getHeight()) {

                    int patchSize = Math.max(sourceMaskBitmap.getWidth(), sourceMaskBitmap.getHeight());

                    // Ensure patch size is valid
                    if (patchSize > 0) {
                        // Perform inpainting, passing source and target masks
                        myInpaint(srcBitmap, sourceMaskBitmap, targetMaskBitmap, patchSize);
                        mProgressBar.setVisibility(View.GONE);
                    } else {
                        // Handle invalid patch size
                        Log.e("Inpaint", "Invalid patch size");
                    }
                } else {
                    // Handle mask bitmap size mismatch error
                    Log.e("Inpaint", "Mask bitmap size does not match the input image size");
                }} else {
                // Handle error: Null bitmaps
                Log.e("Inpaint", "Null bitmaps detected");
            }
        });
 /**
     * A native method that is implemented by the 'opencvnativeinpaint' native library,
     * which is packaged with this application.
     */
    //public native String stringFromJNI();
    public native void myFlip(Bitmap bitmapIn, Bitmap bitmapOut);
    public native void myBlur(Bitmap bitmapIn, Bitmap bitmapOut, float sigma);
    public native void myInpaint(Bitmap bitmapIn, Bitmap sourceMaskBitmap, Bitmap targetMaskBitmap, int patchSize);
`

NOw below is my JNI Call

`extern "C" JNIEXPORT void JNICALL
Java_com_example_yrmultimediaco_opencvnativeinpaint_MainActivity_myInpaint(
        JNIEnv* env, jobject,
        jobject bitmapIn, jobject sourceMaskBitmap, jobject targetMaskBitmap, jint patchSize) {

    // Convert input bitmaps to Mat
    Mat src, sourceMask, targetMask;
    bitmapToMat(env, bitmapIn, src, false);
    bitmapToMat(env, sourceMaskBitmap, sourceMask, false);
    bitmapToMat(env, targetMaskBitmap, targetMask, false);

    // Ensure the input image format is 3 channels (RGB) with 8-bit depth (CV_8U)
    if (src.channels() == 4) {
        // If the image has 4 channels (likely ARGB or RGBA), convert it to 3 channels (RGB)
        cvtColor(src, src, cv::COLOR_RGBA2RGB);

        // Check number of channels and depth in src (input image)
        if (src.channels() == 3 && src.depth() == CV_8U) { // For ARGB_8888 format

            __android_log_print(ANDROID_LOG_DEBUG, "MyInpaint", "Image properties are valid.");

            // Check mask sizes
            if (targetMask.size() == src.size() && (sourceMask.empty() || targetMask.size() == sourceMask.size())) {

                __android_log_print(ANDROID_LOG_DEBUG, "MyInpaint", "Mask sizes are valid.");

                // Check patch size
                if (patchSize > 0) {

                    __android_log_print(ANDROID_LOG_DEBUG, "MyInpaint", "Patch size is valid.");

                    // Perform inpainting using the Criminisi algorithm
                    Inpaint::inpaintCriminisi(src, sourceMask, targetMask, patchSize);

                    // Convert the output Mat back to a Bitmap
                    matToBitmap(env, src, bitmapIn, false);

                } else {
                    __android_log_print(ANDROID_LOG_ERROR, "MyInpaint", "Invalid patch size.");
                    // Handle error: Patch size is not valid
                    // Log an error or throw an exception
                }

            } else {
                __android_log_print(ANDROID_LOG_ERROR, "MyInpaint", "Mask sizes don't meet the required conditions.");
                // Handle error: Mask sizes don't meet the required conditions
                // Log an error or throw an exception
            }

        } else {
            __android_log_print(ANDROID_LOG_ERROR, "MyInpaint", "Image doesn't meet the required conditions.");
            // Handle error: Image doesn't meet the required conditions
            // Log an error or throw an exception
        }

    } else if (src.channels() != 3 || src.depth() != CV_8U) {
        // If the image doesn't meet the required format, handle the error accordingly
        // Log an error or throw an exception
        __android_log_print(ANDROID_LOG_ERROR, "MyInpaint", "Invalid input image format");
        return;
    }

    // Check properties before inpainting

    __android_log_print(ANDROID_LOG_DEBUG, "MyInpaint", "Input image channels: %d, depth: %d", src.channels(), src.depth());
    __android_log_print(ANDROID_LOG_DEBUG, "MyInpaint", "Input image size: %dx%d", src.cols, src.rows);
    __android_log_print(ANDROID_LOG_DEBUG, "MyInpaint", "Target Mask size: %dx%d", targetMask.cols, targetMask.rows);
    __android_log_print(ANDROID_LOG_DEBUG, "MyInpaint", "Source Mask size: %dx%d", sourceMask.cols, sourceMask.rows);


}`

Function which I am using

` void inpaintCriminisi(
        cv::InputArray image,
        cv::InputArray targetMask,
        cv::InputArray sourceMask,        
        int patchSize)
    {
        CriminisiInpainter ci;
        ci.setSourceImage(image.getMat());
        ci.setSourceMask(sourceMask.getMat());
        ci.setTargetMask(targetMask.getMat());
        ci.setPatchSize(patchSize);
        ci.initialize();
        
        while (ci.hasMoreSteps()) {
            ci.step();
        }

        ci.image().copyTo(image.getMat());
    }
}`

Analyze the code and correct the java and C++ interaction code

**Comment by scribblemaniac** [comment]
It doesn't matter how you call it. This library has a bug, and you need to fix it to get rid of this issue. Either apply the changes suggested above manually, or use my branch from pull request #18 which contains the same fix.

**Comment by cheind** [comment]
@codenia sorry for the inconvenience and @scribblemaniac thanks for responding. As the author, I have to admit, I don't have much spare-time left to fix issues. However, PRs are welcome and will be merged after review.

Happy holidays!

**Comment by scribblemaniac** [comment]
> PRs are welcome and will be merged after review.

I can relate to not having enough time for everything. When I submit PRs, I don't expect them to always get merged, especially in personal repositories like this one. But to hear you make this claim about welcoming PRs while mine has sat open in this repo for over 4 years without so much as a comment is more than a little irritating. :confused:

**Comment by cheind** [comment]
@scribblemaniac this is definitely a problem on my side and it was not my intention to cause irritation here. Very sorry! I'll review it ASAP and merge.
