### ISSUE TITLE
About inpaint in 3D space

### ISSUE THREAD

**Issue by AwenHuang** [cheind/inpaint#4]
Hello, I had use your 2D inpainting and I'm think about 3D inpainting.

Can I use your 2D inpaint to 3D ? Do you think it is possible? Can you give me some advice? 

Thank you so much!

**Comment by cheind** [comment]
Hi, could you elaborate what you are trying to inpaint in 3D? I'm thinking about volumetric vs. surface inpainting.

**Comment by cheind** [comment]
Closing this
