### ISSUE TITLE
Help: Any Reverse Function of Inpaint?

### ISSUE THREAD

**Issue by davidsonic** [cheind/inpaint#5]
Inpaint is fantastic! However, I came across a problem where the reverse function of Inpaint is required. Unlike Inpaint which removes an object without trace, Is there any algorithm that you know of could add an object to the original image without visible trace? Although I could add an foreground image directly, but it obviously doesn't blend well with the background image. Much appreciation if you could offer some hint!

**Comment by cheind** [comment]
Hi, not sure if I understand you correctly: Adding an object to an image in a seamless way could be done through Poisson editing methods such as this one here

https://github.com/cheind/poisson-image-editing

As you can see right in the intro, first an object (jet) is copied from one image onto another image in a naive way. Next to it you find the same result but applying Poisson image editing methods.

**Comment by davidsonic** [comment]
Yes, that's exactly what I am looking for!  It's very helpful! Thank you very much!

**Comment by cheind** [comment]
You're welcome.
