### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by michaelitvin** [cheind/inpaint#7]
I'm trying to build inpaint in Xcode 8 with C++11 and OpenCV 2.3.1.
Added the files from /src to the project and compiled. Getting many errors that seem related to OpenCV compatibility:

![image](https://cloud.githubusercontent.com/assets/5813969/22746879/ffcf987a-ee2d-11e6-97f3-8e06d9374d04.png)

**Comment by cheind** [comment]
You are using quite an outdated OpenCV. Any chance you could try to use a
newer version?

Michael Litvin <notifications@github.com> schrieb am Mi., 8. Feb. 2017 um
17:46 Uhr:

**Comment by michaelitvin** [comment]
What versions should be supported?

**Comment by cheind** [comment]
2.4, 3.1

Michael Litvin <notifications@github.com> schrieb am Do., 9. Feb. 2017 um
10:34 Uhr:

**Comment by michaelitvin** [comment]
Thanks

**Comment by cheind** [comment]
Works as expected?

Michael Litvin <notifications@github.com> schrieb am Do., 9. Feb. 2017 um
18:47 Uhr:

**Comment by cheind** [comment]
Assuming to be fixed.

**Comment by michaelitvin** [comment]
Updated to 3.2.
Most errors are fixed, except this error in meanshift.cpp:
![image](https://cloud.githubusercontent.com/assets/5813969/22862776/d0026556-f13d-11e6-80b4-e707ccd76076.png)

I believe that happens because `seeds.row(count)` is a temporary and therefore should be const. If I add `const` on line 34 it compiles fine:
![image](https://cloud.githubusercontent.com/assets/5813969/22862848/52e2163c-f13f-11e6-8349-d7a1177c08a5.png)

**Comment by cheind** [comment]
ok, thanks. I've changed that in master. Note, meanshift.cpp is currently
not used by CMakeLists.txt which is why the error hasn't popped up earlier.
How did you generate your solution file for build?

Best,
Christoph

Michael Litvin <notifications@github.com> schrieb am So., 12. Feb. 2017 um
15:22 Uhr:

**Comment by michaelitvin** [comment]
I haven't used CMake, just added all the cpp files to a project. Should I remove meanshift?

**Comment by cheind** [comment]
No its fine as long as it compiles.

Best,
Christoph

Michael Litvin <notifications@github.com> schrieb am So., 12. Feb. 2017 um
16:00 Uhr:

**Comment by michaelitvin** [comment]
Thanks
