### ISSUE TITLE
potential bug

### ISSUE THREAD

**Issue by hjwdzh** [cheind/inpaint#8]
I think there might be a bug in updatefillfront. The confidence should be an average of confidence of the last step. However, some new confidence values are updated and used when computing the neighbor's confidence.

I am not sure if you intentionally make it this way, or it is a bug.

**Comment by cheind** [comment]
@hjwdzh not sure what you mean. AFAIK `updatefillfront` is called as the first method in `CriminisiInpainter::step()`. Therefore I'm unaware how the inpainter could mix old and potentially new values?

**Comment by cheind** [comment]
Closing this, reopen if you have more details.
