### ISSUE TITLE
Help in running

### ISSUE THREAD

**Issue by pradyoth-hegde** [cheind/inpaint#9]
Hi, sorry to sound like a real noob.
But, any pointers on how to run this program would be extremely helpful!

Thanks

**Comment by cheind** [comment]
Hi,

- follow the build instructions  https://github.com/cheind/inpaint
- launch `inpaint_image_criminisi <image>`
- use mouse and left button down to draw area to be painted
- optionally use mouse and right button down to limit area to take samples from
- press 'e' to inpaint.

hth,
Christoph

**Comment by pradyoth-hegde** [comment]
I have never used CMake and have only used OpenCV with Python.
More step by step instructions would be appreciated.
Sorry again.

**Comment by cheind** [comment]
Hi, sorry but this is not the place to give those instructions. You might want to familiarize yourself with CMAKE and C++ Compilers first. Here's a head start

https://cmake.org/cmake-tutorial/

Best luck,
Christoph
